// Mock data seeded from backend/db JSON files
// Used when MOCK_DATA = true in mockConfig.ts

export const MOCK_RESTAURANTS = [
  {
    id: "r1",
    name: "Pizza Palace",
    image: "https://i.ibb.co/23S908KH/r1.jpg",
    cuisineType: "Pizza",
    cuisineIcon: "https://i.ibb.co/83gV8bk/c1.png",
    address: "101 Pike St, Seattle, WA 98101",
    latitude: 47.60895,
    longitude: -122.336472,
    rating: 4.7,
    ratingCount: 320,
    deliveryTimeEst: 25,
    deliveryFee: 2.99,
    isActive: true,
  },
  {
    id: "r2",
    name: "Burger Barn",
    image: "https://i.ibb.co/yFV0YcPN/r2.jpg",
    cuisineType: "Burgers",
    cuisineIcon: "https://i.ibb.co/CsV5W1Fr/c2.png",
    address: "202 Broad St, Seattle, WA 98102",
    latitude: 47.619962,
    longitude: -122.322248,
    rating: 4.4,
    ratingCount: 215,
    deliveryTimeEst: 20,
    deliveryFee: 1.99,
    isActive: true,
  },
  {
    id: "r3",
    name: "Sushi Spot",
    image: "https://i.ibb.co/LXdyvs2N/r3.jpg",
    cuisineType: "Sushi",
    cuisineIcon: "https://i.ibb.co/F4m8PQtx/c3.png",
    address: "303 Union St, Seattle, WA 98103",
    latitude: 47.604724,
    longitude: -122.338761,
    rating: 4.8,
    ratingCount: 410,
    deliveryTimeEst: 35,
    deliveryFee: 3.99,
    isActive: true,
  },
  {
    id: "r4",
    name: "Taco Town",
    image: "https://i.ibb.co/LF3Yq6J/r4.jpg",
    cuisineType: "Mexican",
    cuisineIcon: "https://i.ibb.co/0jcsBTGz/c4.png",
    address: "404 Cedar Ave, Seattle, WA 98104",
    latitude: 47.60189,
    longitude: -122.322657,
    rating: 4.5,
    ratingCount: 180,
    deliveryTimeEst: 22,
    deliveryFee: 2.49,
    isActive: true,
  },
  {
    id: "r5",
    name: "Sweet Treats",
    image: "https://i.ibb.co/Xx05g6Xq/r5.jpg",
    cuisineType: "Desserts",
    cuisineIcon: "https://i.ibb.co/zh19F0v4/c5.png",
    address: "505 Maple Blvd, Seattle, WA 98105",
    latitude: 47.618583,
    longitude: -122.337904,
    rating: 4.6,
    ratingCount: 290,
    deliveryTimeEst: 18,
    deliveryFee: 1.49,
    isActive: true,
  },
  {
    id: "r6",
    name: "Wok & Roll",
    image: "https://i.ibb.co/ym0zwPTf/r6.jpg",
    cuisineType: "Asian",
    cuisineIcon: "https://i.ibb.co/hx7f75xn/c6.png",
    address: "606 Pine St, Seattle, WA 98106",
    latitude: 47.609525,
    longitude: -122.325,
    rating: 4.5,
    ratingCount: 198,
    deliveryTimeEst: 28,
    deliveryFee: 2.49,
    isActive: true,
  },
  {
    id: "r7",
    name: "Green Bowl",
    image: "https://i.ibb.co/0RxPWL8g/r7.jpg",
    cuisineType: "Healthy",
    cuisineIcon: "https://i.ibb.co/mVK46yLF/c7.png",
    address: "808 Seneca St, Seattle, WA 98108",
    latitude: 47.599224,
    longitude: -122.328746,
    rating: 4.7,
    ratingCount: 176,
    deliveryTimeEst: 20,
    deliveryFee: 2.99,
    isActive: true,
  },
];

export const MOCK_MENU_ITEMS = [
  { id: "m1", restaurantId: "r1", name: "Margherita Pizza", price: 12.99 },
  { id: "m2", restaurantId: "r1", name: "Pepperoni Pizza", price: 14.99 },
  { id: "m3", restaurantId: "r1", name: "Garlic Bread", price: 4.99 },
  { id: "m4", restaurantId: "r1", name: "Tiramisu", price: 6.99 },
  { id: "m5", restaurantId: "r1", name: "Sparkling Water", price: 2.49 },
  { id: "m6", restaurantId: "r2", name: "Classic Smash Burger", price: 10.99 },
  { id: "m7", restaurantId: "r2", name: "BBQ Bacon Burger", price: 13.49 },
  { id: "m8", restaurantId: "r2", name: "Crispy Fries", price: 3.99 },
  { id: "m9", restaurantId: "r2", name: "Chocolate Milkshake", price: 5.49 },
  { id: "m10", restaurantId: "r3", name: "Salmon Nigiri (2 pcs)", price: 7.99 },
  { id: "m11", restaurantId: "r3", name: "Dragon Roll (8 pcs)", price: 15.99 },
  { id: "m12", restaurantId: "r3", name: "Miso Soup", price: 2.99 },
  { id: "m13", restaurantId: "r3", name: "Matcha Ice Cream", price: 4.99 },
  { id: "m14", restaurantId: "r4", name: "Street Tacos (3 pcs)", price: 9.99 },
  { id: "m15", restaurantId: "r4", name: "Burrito Bowl", price: 11.49 },
  { id: "m16", restaurantId: "r4", name: "Chips & Salsa", price: 3.49 },
  { id: "m17", restaurantId: "r4", name: "Horchata", price: 3.99 },
  { id: "m18", restaurantId: "r5", name: "Nutella Crepe", price: 8.49 },
  { id: "m19", restaurantId: "r5", name: "Waffle Stack", price: 9.99 },
  { id: "m20", restaurantId: "r5", name: "Bubble Tea", price: 5.99 },
  { id: "m21", restaurantId: "r6", name: "Kung Pao Chicken", price: 13.99 },
  { id: "m22", restaurantId: "r6", name: "Beef Pho", price: 12.99 },
  { id: "m23", restaurantId: "r7", name: "Quinoa Power Bowl", price: 13.49 },
  { id: "m24", restaurantId: "r7", name: "Acai Smoothie Bowl", price: 10.99 },
];

export const MOCK_USERS = [
  {
    id: "1",
    name: "John D.",
    email: "admin@example.com",
    addresses: [
      { street: "123 Main St", city: "Seattle", latitude: 47.6205, longitude: -122.3493 }
    ],
  },
  {
    id: "2",
    name: "Jane D.",
    email: "demo@example.com",
    addresses: [
      { street: "789 Pine Rd", city: "Seattle", latitude: 47.6062, longitude: -122.3321 },
    ],
  },
  // Extra synthetic users for variety in the demo
  {
    id: "3",
    name: "Alex M.",
    email: "alex@example.com",
    addresses: [
      { street: "321 Bell St", city: "Seattle", latitude: 47.6145, longitude: -122.3415 },
    ],
  },
  {
    id: "4",
    name: "Sam K.",
    email: "sam@example.com",
    addresses: [
      { street: "555 Eastlake Ave", city: "Seattle", latitude: 47.6302, longitude: -122.3287 },
    ],
  },
  {
    id: "5",
    name: "Riley T.",
    email: "riley@example.com",
    addresses: [
      { street: "88 Capitol Hill Blvd", city: "Seattle", latitude: 47.6233, longitude: -122.3148 },
    ],
  },
];
